[package]
name = "test_crate_hello_world"
version = "0.1.0"
authors = ["vaneEmy <vanvanemily@gmail.com>"]

description = "A Simple Hello World Crate"
keywords = ["Hello", "world"]
license = "Apache-2.0"
[dependencies]
